import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
  banner: { js: banner },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    // Native modules — must be external in Electron
    'onnxruntime-node',
    'sharp',
    ...builtins],
  format: 'cjs',
  target: 'es2020',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  platform: 'node',
}).then(() => {
  // Post-build patches for Obsidian Electron compatibility
  let code = fs.readFileSync('main.js', 'utf8');

  // 1. Wrap native module requires in try/catch
  code = code.replace(
    /var (\w+) = __toESM\(require\("onnxruntime-node"\), 1\);/g,
    'var $1 = (() => { try { return __toESM(require("onnxruntime-node"), 1); } catch(e) { return { default: null }; } })();'
  );
  code = code.replace(
    /var (\w+) = __toESM\(require\("sharp"\), 1\);/g,
    'var $1 = (() => { try { return __toESM(require("sharp"), 1); } catch(e) { return { default: null }; } })();'
  );

  // 2. Force ONNX_WEB backend in Obsidian Electron
  //    @xenova/transformers checks process.release.name === "node" → true in Electron
  //    → tries onnxruntime-node (unavailable) → ONNX = null → crash
  code = code.replace(
    /if \(typeof process !== "undefined" && process\?\.release\?\.name === "node"\) \{\s*\n\s*ONNX = ONNX_NODE\.default \?\? ONNX_NODE;\s*\n\s*executionProviders\.unshift\("cpu"\);\s*\n\s*\} else \{\s*\n\s*ONNX = ONNX_WEB\.default \?\? ONNX_WEB;/g,
    'ONNX = ONNX_NODE?.default ? ONNX_NODE.default : ONNX_WEB.default ?? ONNX_WEB;\n  if (false) {\n    ONNX = ONNX_NODE.default ?? ONNX_NODE;\n    executionProviders.unshift("cpu");\n  } else {\n    ONNX = ONNX_WEB.default ?? ONNX_WEB;'
  );

  // 3. Force onnxruntime-web WASM module into browser mode
  //    The bundled ort-web.node.js detects process.versions.node → enters Node path
  //    → requires worker_threads, fs, path, process.exit() → all crash in Obsidian Electron
  //    Fix: override the 'w' (isNode) variable to false in the Emscripten module
  code = code.replace(
    /w = "object" == typeof process && "object" == typeof process\.versions && "string" == typeof process\.versions\.node/g,
    'w = false'
  );

  // 4. Patch @xenova/transformers env detection to not use FS/PATH
  //    RUNNING_LOCALLY causes it to look for local model files via fs/path
  code = code.replace(
    /var RUNNING_LOCALLY = FS_AVAILABLE && PATH_AVAILABLE;/g,
    'var RUNNING_LOCALLY = false;'
  );

  fs.writeFileSync('main.js', code);
  console.log('  ✓ Patched native requires + ONNX backend + WASM browser mode');
}).catch(() => process.exit(1));
